function apply_confirmed_association_fix(target_file)
%APPLY_CONFIRMED_ASSOCIATION_FIX Patch the evaluator in-place, no package dependency.
%
% Usage:
%   apply_confirmed_association_fix
%
% The patch only changes collect_confirmed_ids() inside
% evaluate_joint_tracking_metrics.m. It does NOT change filtering,
% association, track management, or 2-D/3-D switching.

root = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(target_file)
    target_file = fullfile(root, 'evaluate_joint_tracking_metrics.m');
end

if ~exist(target_file, 'file')
    error('apply_confirmed_association_fix:MissingEvaluator', ...
        '找不到评价器: %s', target_file);
end

text = fileread(target_file);

% Recover automatically from the previous package-wrapper version if the
% complete old branch was downloaded. This keeps the v2 patch usable for
% users who already replaced the root evaluator once.
if contains(text, 'metriclegacy.evaluate_joint_tracking_metrics')
    legacy_file = fullfile(root, '+metriclegacy', 'evaluate_joint_tracking_metrics.m');
    if exist(legacy_file, 'file')
        fprintf('[评价修复] 检测到上一版 package 包装器，先恢复原评价器。\n');
        text = fileread(legacy_file);
    else
        error('apply_confirmed_association_fix:BrokenV1WithoutLegacy', ...
            ['当前 evaluate_joint_tracking_metrics.m 是上一版包装器，但本地缺少 ', ...
             '+metriclegacy/evaluate_joint_tracking_metrics.m。请重新下载 v2 分支完整 ZIP。']);
    end
end

if contains(text, 'CONFIRMED_ASSOCIATION_FIX_V2')
    fprintf('[评价修复] 已是 v2 修正版，无需重复修改。\n');
    return;
end

start_token = 'function ids = collect_confirmed_ids(est, fallback_output_ids)';
end_token = 'function n = get_transition_count(est)';
start_idx = strfind(text, start_token);
end_idx = strfind(text, end_token);
if numel(start_idx) ~= 1 || numel(end_idx) ~= 1 || end_idx <= start_idx
    error('apply_confirmed_association_fix:UnexpectedEvaluatorLayout', ...
        '未找到唯一的 collect_confirmed_ids/get_transition_count 函数边界，停止修改以避免破坏文件。');
end

replacement = [ ...
'function ids = collect_confirmed_ids(est, fallback_output_ids)' newline ...
'% CONFIRMED_ASSOCIATION_FIX_V2' newline ...
'% "曾确认"必须按逻辑航迹全生命周期回溯，而不能把 transition_log 当作唯一来源。' newline ...
'% legacy 3-D backbone 的成熟航迹通常直接进入正式输出；维度管理器的 transition_log' newline ...
'% 并不保证记录所有这些 3-D ID。正确做法是取所有可靠确认依据的并集。' newline ...
'' newline ...
'% 正式逻辑输出本身就是最直接的确认依据。fallback_output_ids 来自 est.output，' newline ...
'% shadow 3-D candidate 不在 est.output 中，因此不会被误计。' newline ...
'ids = reshape(fallback_output_ids, 1, []);' newline ...
'' newline ...
'% 显式 logical_confirm_* transition：补充 confirmed-into-hold 等尚未正式输出的航迹。' newline ...
'if isstruct(est) && isfield(est, ''transition_log'') && ~isempty(est.transition_log)' newline ...
'    log = est.transition_log;' newline ...
'    if isstruct(log) && isfield(log, ''id'') && isfield(log, ''reason'')' newline ...
'        reasons = {log.reason};' newline ...
'        is_confirm = false(size(reasons));' newline ...
'        for q = 1:numel(reasons)' newline ...
'            reason = reasons{q};' newline ...
'            is_confirm(q) = ischar(reason) && strncmp(reason, ''logical_confirm_'', 16);' newline ...
'        end' newline ...
'        if any(is_confirm)' newline ...
'            values = reshape([log(is_confirm).id], 1, []);' newline ...
'            ids = [ids, values]; %#ok<AGROW>' newline ...
'        end' newline ...
'    end' newline ...
'end' newline ...
'' newline ...
'% 诊断/full history 模式下保留的 confirmed logical-track snapshots。' newline ...
'if isstruct(est) && isfield(est, ''logical_tracks'') && ~isempty(est.logical_tracks)' newline ...
'    for k = 1:numel(est.logical_tracks)' newline ...
'        tracks = est.logical_tracks{k};' newline ...
'        if isempty(tracks) || ~isstruct(tracks) || ~isfield(tracks, ''id'') || ...' newline ...
'                ~isfield(tracks, ''confirmed'')' newline ...
'            continue;' newline ...
'        end' newline ...
'        confirmed = logical([tracks.confirmed]);' newline ...
'        if any(confirmed)' newline ...
'            values = reshape([tracks(confirmed).id], 1, []);' newline ...
'            ids = [ids, values]; %#ok<AGROW>' newline ...
'        end' newline ...
'    end' newline ...
'end' newline ...
'' newline ...
'% L/L2 是正式 3-D/2-D 输出标签矩阵，再作为兼容性确认依据。' newline ...
'for name_cell = {''L'', ''L2''}' newline ...
'    name = name_cell{1};' newline ...
'    if ~isstruct(est) || ~isfield(est, name) || isempty(est.(name)), continue; end' newline ...
'    cells = est.(name);' newline ...
'    for k = 1:numel(cells)' newline ...
'        L = cells{k};' newline ...
'        if isempty(L) || size(L, 2) < 2, continue; end' newline ...
'        values = reshape(L(:, 2), 1, []);' newline ...
'        ids = [ids, values]; %#ok<AGROW>' newline ...
'    end' newline ...
'end' newline ...
'' newline ...
'ids = unique(ids(isfinite(ids)));' newline ...
'end' newline newline];

new_text = [text(1:start_idx-1), replacement, text(end_idx:end)];

% Make a backup only if it does not already exist.
backup = [target_file, '.pre_confirmed_metric_fix.bak'];
if ~exist(backup, 'file')
    fid = fopen(backup, 'w', 'n', 'UTF-8');
    assert(fid >= 0, '无法创建备份文件: %s', backup);
    cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fwrite(fid, text, 'char');
    clear cleanup;
end

fid = fopen(target_file, 'w', 'n', 'UTF-8');
assert(fid >= 0, '无法写入评价器: %s', target_file);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, new_text, 'char');
clear cleanup;

clear evaluate_joint_tracking_metrics;
rehash;
fprintf('[评价修复] 已完成: %s\n', target_file);
fprintf('[评价修复] 仅修改“曾确认逻辑航迹ID”的回溯口径；滤波器本体未改。\n');
end
