function apply_3d2d_control_fix(root)
%APPLY_3D2D_CONTROL_FIX Switch 3D->2D degradation to two physical indicators.
%
% Degradation control after this patch:
%   1) radial/range 95%% uncertainty; and
%   2) elapsed time since the last range-capable active 3-D update.
%
% Position-95, relative range uncertainty and spatial NIS remain available
% as diagnostics, but no longer directly trigger warn/down/recover state.
% Existing debounce and handoff protection are preserved:
%   - joint_down_consecutive consecutive down decisions;
%   - valid 2-D angle branch;
%   - 2-D/3-D switch consistency gate.
%
% The mature-3D branch disappearance fail-safe (external_3d_lost) is also
% preserved because there is no spatial branch left to output in that case.

if nargin < 1 || isempty(root)
    root = fileparts(mfilename('fullpath'));
end
filter_file = fullfile(root, 'run_filter_joint_2d3d.m');
config_file = fullfile(root, 'config_fusion.m');
validate_file = fullfile(root, 'validate_config_fusion.m');

assert(exist(filter_file, 'file') == 2, '找不到 %s', filter_file);
assert(exist(config_file, 'file') == 2, '找不到 %s', config_file);
assert(exist(validate_file, 'file') == 2, '找不到 %s', validate_file);

patch_filter(filter_file);
patch_config(config_file);
patch_validation(validate_file);

clear run_filter_joint_2d3d config_fusion validate_config_fusion;
rehash;
fprintf('[3D->2D控制修复] 已启用：距离95%%不确定度 + 主动三维量测缺失时间。\n');
fprintf('[3D->2D控制修复] 保留连续判定、2D可用性和跨维一致性保护。\n');
end

function patch_filter(path)
text = normalize_newlines(fileread(path));
if contains(text, 'RANGE_ACTIVE_MISSING_3D2D_V1')
    fprintf('[3D->2D控制修复] run_filter_joint_2d3d.m 已是最新版。\n');
    return;
end
backup_once(path, text);

old = join_lines({ ...
"p.radial95_warn_m = get_cfg(cfg, 'joint_radial95_warn_m', 10000);", ...
"p.radial95_down_m = get_cfg(cfg, 'joint_radial95_down_m', 20000);", ...
"p.radial95_recover_m = get_cfg(cfg, 'joint_radial95_recover_m', 7000);", ...
"p.relative_range_down = get_cfg(cfg, 'joint_relative_range_down', 0.60);"});
new = join_lines({ ...
"p.radial95_warn_m = get_cfg(cfg, 'joint_radial95_warn_m', 10000);", ...
"p.radial95_down_m = get_cfg(cfg, 'joint_radial95_down_m', 20000);", ...
"p.radial95_recover_m = get_cfg(cfg, 'joint_radial95_recover_m', 7000);", ...
"% RANGE_ACTIVE_MISSING_3D2D_V1: active 3-D means range-capable active update.", ...
"p.active3d_missing_warn_s = get_cfg(cfg, 'joint_active3d_missing_warn_s', 0.20);", ...
"p.active3d_missing_down_s = get_cfg(cfg, 'joint_active3d_missing_down_s', 0.30);", ...
"p.active3d_missing_recover_s = get_cfg(cfg, 'joint_active3d_missing_recover_s', 0.15);", ...
"% Legacy quality terms are retained for diagnostics only.", ...
"p.relative_range_down = get_cfg(cfg, 'joint_relative_range_down', 0.60);"});
text = replace_once(text, old, new, 'joint parameter insertion');

old = join_lines({ ...
"    companions(i).last_update_t = t;", ...
"    companions(i).last_angle_observation_t = t;", ...
"    if update_kind(q) == 2", ...
"        companions(i).last_active_t = t;", ...
"    else", ...
"        companions(i).last_passive_t = t;", ...
"    end"});
new = join_lines({ ...
"    companions(i).last_update_t = t;", ...
"    companions(i).last_angle_observation_t = t;", ...
"    % Active AE-only observations are angular updates, not range-capable", ...
"    % active 3-D measurements. They must not refresh last_active_t, because", ...
"    % that timestamp now drives the 3-D active-measurement-missing timer.", ...
"    if update_kind(q) ~= 2", ...
"        companions(i).last_passive_t = t;", ...
"    end"});
text = replace_once(text, old, new, 'active-AE timestamp semantics');

start_token = 'function q = assess_quality(tr, sensor, p)';
start_idx = locate_once(text, start_token, 'assess_quality');
angle_token = 'if tr.angle.valid && tr.space.valid';
angle_rel = strfind(text(start_idx:end), angle_token);
if numel(angle_rel) ~= 1
    error('apply_3d2d_control_fix:AssessQualityLayout', ...
        '无法唯一定位 assess_quality 的跨维一致性段。');
end
angle_idx = start_idx + angle_rel(1) - 1;
space_token = 'if tr.space.valid';
space_rel = strfind(text(start_idx:angle_idx-1), space_token);
if numel(space_rel) ~= 1
    error('apply_3d2d_control_fix:AssessQualityLayout', ...
        '无法唯一定位 assess_quality 的三维质量段。');
end
space_idx = start_idx + space_rel(1) - 1;
new_space = join_lines({ ...
"if tr.space.valid", ...
"    Pp = make_spd(tr.space.P([1, 4, 7], [1, 4, 7]));", ...
"    rel = tr.space.x([1, 4, 7]) - sensor; q.range_m = norm(rel);", ...
"    if q.range_m > 0, u = rel / q.range_m; else, u = [1; 0; 0]; end", ...
"    q.radial_sigma_m = sqrt(max(u' * Pp * u, 0));", ...
"    q.radial95_m = 1.96 * q.radial_sigma_m;", ...
"    q.position95_m = sqrt(7.8147279 * max(real(eig(Pp))));", ...
"    q.relative_range_sigma = q.radial_sigma_m / max(q.range_m, 1);", ...
"", ...
"    % New degradation indicator #2: elapsed time since the last", ...
"    % range-capable active 3-D update. predict_track/predict_companion keep", ...
"    % tr.last_t synchronized with the current decision time.", ...
"    if isfinite(tr.last_t) && isfinite(tr.last_active_t)", ...
"        q.active3d_missing_s = max(tr.last_t - tr.last_active_t, 0);", ...
"    else", ...
"        q.active3d_missing_s = inf;", ...
"    end", ...
"", ...
"    % Retain NIS and the former position/relative-range terms as diagnostics", ...
"    % only. They no longer directly drive 3-D -> 2-D mode switching.", ...
"    nh = tr.space.nis_norm_history;", ...
"    nh = nh(max(1, end - p.space_nis_window + 1):end);", ...
"    nh = nh(isfinite(nh));", ...
"    if ~isempty(nh), q.nis_norm = median(nh); end", ...
"", ...
"    q.down_by_range_uncertainty = q.radial95_m > p.radial95_down_m;", ...
"    q.down_by_active3d_missing = q.active3d_missing_s > p.active3d_missing_down_s;", ...
"    range_warn = q.radial95_m > p.radial95_warn_m;", ...
"    missing_warn = q.active3d_missing_s > p.active3d_missing_warn_s;", ...
"    range_recover = q.radial95_m <= p.radial95_recover_m;", ...
"    missing_recover = q.active3d_missing_s <= p.active3d_missing_recover_s;", ...
"", ...
"    q.warn3d = range_warn || missing_warn;", ...
"    q.down3d = q.down_by_range_uncertainty || q.down_by_active3d_missing;", ...
"    q.valid3d = ~q.down3d;", ...
"    q.recover3d = range_recover && missing_recover;", ...
"end", ...
""});
text = [text(1:space_idx-1), new_space, text(angle_idx:end)];

old = join_lines({ ...
"function q = quality_template()", ...
"q = struct('valid2d', false, 'valid3d', false, 'warn3d', false, ...", ...
"    'down3d', true, 'recover3d', false, 'switch_consistent', false, ...", ...
"    'observed2d', false, ...", ...
"    'angle95_deg', inf, 'position95_m', inf, 'radial_sigma_m', inf, ...", ...
"    'radial95_m', inf, 'relative_range_sigma', inf, 'range_m', NaN, ...", ...
"    'switch_nis', inf, 'nis_norm', NaN);", ...
"end"});
new = join_lines({ ...
"function q = quality_template()", ...
"q = struct('valid2d', false, 'valid3d', false, 'warn3d', false, ...", ...
"    'down3d', true, 'recover3d', false, 'switch_consistent', false, ...", ...
"    'observed2d', false, ...", ...
"    'angle95_deg', inf, 'position95_m', inf, 'radial_sigma_m', inf, ...", ...
"    'radial95_m', inf, 'relative_range_sigma', inf, 'range_m', NaN, ...", ...
"    'active3d_missing_s', inf, 'down_by_range_uncertainty', false, ...", ...
"    'down_by_active3d_missing', false, ...", ...
"    'switch_nis', inf, 'nis_norm', NaN);", ...
"end"});
text = replace_once(text, old, new, 'quality template');
write_utf8(path, text);
fprintf('[3D->2D控制修复] 已修改 %s\n', path);
end

function patch_config(path)
text = normalize_newlines(fileread(path));
if contains(text, 'joint_active3d_missing_down_s')
    fprintf('[3D->2D控制修复] config_fusion.m 已包含新参数。\n');
    return;
end
backup_once(path, text);
old = join_lines({ ...
"cfg.joint_pos95_warn_m = 15000;          % 位置95%不确定度预警门[m]", ...
"cfg.joint_pos95_down_m = 30000;          % 位置95%不确定度降级门[m]", ...
"cfg.joint_pos95_recover_m = 10000;       % 位置95%不确定度恢复门[m]", ...
"cfg.joint_radial95_warn_m = 10000;       % 径向95%不确定度预警门[m]", ...
"cfg.joint_radial95_down_m = 20000;       % 径向95%不确定度降级门[m]", ...
"cfg.joint_radial95_recover_m = 7000;     % 径向95%不确定度恢复门[m]", ...
"cfg.joint_relative_range_down = 0.60;    % 相对距离不确定度降级门", ...
"", ...
"cfg.joint_space_nis_window = 5;          % 空间NIS滑窗长度", ...
"cfg.joint_space_nis_recover = 1.5;       % 空间NIS恢复门", ...
"cfg.joint_space_nis_warn = 2.5;          % 空间NIS预警门", ...
"cfg.joint_space_nis_down = 4.0;          % 空间NIS降级门"});
new = join_lines({ ...
"% 3D->2D正式控制指标（仅这两类指标直接驱动质量降级）：", ...
"% 1) 径向距离95%不确定度；2) 距上次带距离主动三维更新的时间。", ...
"cfg.joint_radial95_warn_m = 10000;       % 距离95%不确定度预警门[m]", ...
"cfg.joint_radial95_down_m = 20000;       % 距离95%不确定度降级门[m]", ...
"cfg.joint_radial95_recover_m = 7000;     % 距离95%不确定度恢复门[m]", ...
"cfg.joint_active3d_missing_warn_s = 0.20;    % 主动三维量测缺失预警时间[s]", ...
"cfg.joint_active3d_missing_down_s = 0.30;    % 主动三维量测缺失降级时间[s]", ...
"cfg.joint_active3d_missing_recover_s = 0.15; % 主动三维量测恢复新鲜度门[s]", ...
"", ...
"% 以下指标继续计算/保留，便于诊断，但不再直接触发3D->2D：", ...
"cfg.joint_pos95_warn_m = 15000;          % 位置95%不确定度诊断预警门[m]", ...
"cfg.joint_pos95_down_m = 30000;          % 位置95%不确定度诊断门[m]", ...
"cfg.joint_pos95_recover_m = 10000;       % 位置95%不确定度诊断恢复门[m]", ...
"cfg.joint_relative_range_down = 0.60;    % 相对距离不确定度诊断门", ...
"cfg.joint_space_nis_window = 5;          % 空间NIS滑窗长度（诊断）", ...
"cfg.joint_space_nis_recover = 1.5;       % 空间NIS诊断恢复门", ...
"cfg.joint_space_nis_warn = 2.5;          % 空间NIS诊断预警门", ...
"cfg.joint_space_nis_down = 4.0;          % 空间NIS诊断门"});
text = replace_once(text, old, new, 'config quality block');
write_utf8(path, text);
fprintf('[3D->2D控制修复] 已修改 %s\n', path);
end

function patch_validation(path)
text = normalize_newlines(fileread(path));
if contains(text, "set_default(cfg, 'joint_active3d_missing_down_s'")
    fprintf('[3D->2D控制修复] validate_config_fusion.m 已包含新参数校验。\n');
    return;
end
backup_once(path, text);
old = join_lines({ ...
"cfg = set_default(cfg, 'joint_radial95_warn_m', 10000);", ...
"cfg = set_default(cfg, 'joint_radial95_down_m', 20000);", ...
"cfg = set_default(cfg, 'joint_radial95_recover_m', 7000);"});
new = join_lines({ ...
"cfg = set_default(cfg, 'joint_radial95_warn_m', 10000);", ...
"cfg = set_default(cfg, 'joint_radial95_down_m', 20000);", ...
"cfg = set_default(cfg, 'joint_radial95_recover_m', 7000);", ...
"cfg = set_default(cfg, 'joint_active3d_missing_warn_s', 0.20);", ...
"cfg = set_default(cfg, 'joint_active3d_missing_down_s', 0.30);", ...
"cfg = set_default(cfg, 'joint_active3d_missing_recover_s', 0.15);"});
text = replace_once(text, old, new, 'validation defaults');

old = join_lines({ ...
"must_be_nonnegative(cfg.joint_radial95_recover_m, 'cfg.joint_radial95_recover_m');", ...
"must_be_positive(cfg.joint_radial95_warn_m, 'cfg.joint_radial95_warn_m');", ...
"must_be_positive(cfg.joint_radial95_down_m, 'cfg.joint_radial95_down_m');"});
new = join_lines({ ...
"must_be_nonnegative(cfg.joint_radial95_recover_m, 'cfg.joint_radial95_recover_m');", ...
"must_be_positive(cfg.joint_radial95_warn_m, 'cfg.joint_radial95_warn_m');", ...
"must_be_positive(cfg.joint_radial95_down_m, 'cfg.joint_radial95_down_m');", ...
"must_be_nonnegative(cfg.joint_active3d_missing_recover_s, 'cfg.joint_active3d_missing_recover_s');", ...
"must_be_positive(cfg.joint_active3d_missing_warn_s, 'cfg.joint_active3d_missing_warn_s');", ...
"must_be_positive(cfg.joint_active3d_missing_down_s, 'cfg.joint_active3d_missing_down_s');"});
text = replace_once(text, old, new, 'validation scalar checks');

old = join_lines({ ...
"if ~(cfg.joint_radial95_recover_m < cfg.joint_radial95_warn_m && ...", ...
"        cfg.joint_radial95_warn_m < cfg.joint_radial95_down_m)", ...
"    error('径向误差门限要求 recover < warn < down');", ...
"end"});
new = join_lines({ ...
"if ~(cfg.joint_radial95_recover_m < cfg.joint_radial95_warn_m && ...", ...
"        cfg.joint_radial95_warn_m < cfg.joint_radial95_down_m)", ...
"    error('距离95%%不确定度门限要求 recover < warn < down');", ...
"end", ...
"if ~(cfg.joint_active3d_missing_recover_s < cfg.joint_active3d_missing_warn_s && ...", ...
"        cfg.joint_active3d_missing_warn_s < cfg.joint_active3d_missing_down_s)", ...
"    error('主动三维量测缺失时间门限要求 recover < warn < down');", ...
"end"});
text = replace_once(text, old, new, 'validation threshold ordering');
write_utf8(path, text);
fprintf('[3D->2D控制修复] 已修改 %s\n', path);
end

function text = normalize_newlines(text)
text = strrep(text, sprintf('\r\n'), sprintf('\n'));
text = strrep(text, sprintf('\r'), sprintf('\n'));
end

function out = replace_once(text, old, new, label)
hit = strfind(text, old);
if numel(hit) ~= 1
    error('apply_3d2d_control_fix:UnexpectedLayout', ...
        '补丁步骤 %s 期望唯一匹配，实际匹配数=%d。', label, numel(hit));
end
out = [text(1:hit-1), new, text(hit+length(old):end)];
end

function idx = locate_once(text, token, label)
hit = strfind(text, token);
if numel(hit) ~= 1
    error('apply_3d2d_control_fix:UnexpectedLayout', ...
        '定位 %s 期望唯一匹配，实际匹配数=%d。', label, numel(hit));
end
idx = hit(1);
end

function text = join_lines(lines)
text = strjoin(cellstr(string(lines)), newline);
end

function backup_once(path, text)
backup = [path, '.pre_3d2d_control_fix.bak'];
if exist(backup, 'file') == 2, return; end
write_utf8(backup, text);
end

function write_utf8(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
assert(fid >= 0, '无法写入文件: %s', path);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', text);
end
